FROM node:14

# Create a directory for the app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all other source code to the container
COPY . .

# Expose port 3000 (the port on which your Express app runs)
EXPOSE 3001

# Command to run the application
CMD ["node", "index.js"]
